name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for contributing to this project by raising an issue. I will get back to you as soon as possible.'
        pr-message: 'Wonderful! It was your first contribution in this project and that is AWESOME!'
